# Generated by Django 4.0 on 2021-12-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpassword',
            name='email',
            field=models.EmailField(default='cool', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformpassword',
            name='username',
            field=models.CharField(default='cool@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
